spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mts
    username: postgres
    password: 1234567890
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    user: postgres
    password: 1234567890
    default-schema: animals
    locations: classpath:/db/migration
    baseline-on-migrate: true

  security:
    secret:
      access: 4279ad0b6d61517bfd37b117c983ac51c8cdc6b426e67d1aafb0b70392a1388e
      expiration: 300

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

server:
  port: 8081

logging:
  level:
    org:
      thymeleaf: DEBUG
      springframework: DEBUG